---
- name: PKI - Ensure private key and csr exists
  ansible.builtin.include_tasks:
    file: _privatekey-csr.yml

- name: PKI - Self-signed - Ensure certificate exist
  delegate_to: localhost
  community.crypto.x509_certificate:
    path: "{{ pki_certificate_file_path }}"
    csr_content: "{{ pki_csr_registry.csr }}"
    privatekey_path: "{{ pki_certificate_key_file_path }}"
    provider: selfsigned
    selfsigned_not_after: "{{ pki_certificate_not_after }}"
