---
- name: Task[user.yml] - Ensure group exist
  ansible.builtin.group:
    name: "{{ common_user_group }}"
    state: present

- name: Task[user.yml] - Ensure user exist and belongs to the group
  ansible.builtin.user:
    name: "{{ common_user_name }}"
    group: "{{ common_user_group }}"
    system: true
    create_home: true
    home: "{{ common_user_home_path }}"
